! Keepalived configuration for bender (MASTER)

global_defs {
    router_id PIHOLE_BENDER
}

vrrp_script chk_pihole {
    script "/bin/sh -c '/usr/bin/wget -q --spider --timeout=2 http://127.0.0.1:8053/admin/'"
    interval 2
    weight -150
    fall 3
    rise 2
}

vrrp_instance PIHOLE_VIP {
    state MASTER
    interface bond0
    virtual_router_id 53
    priority 200
    advert_int 1
    
    authentication {
        auth_type PASS
        auth_pass vuJow9aE8qKa7oZdsAsfz6Sc5Mm5dj8t
    }
    
    unicast_src_ip 192.168.21.121
    unicast_peer {
        192.168.21.130
    }
    
    virtual_ipaddress {
        192.168.21.100/24 dev bond0
    }
    
    track_script {
        chk_pihole
    }
}
